on:
  workflow_dispatch:

jobs:
  live-streaming:
    runs-on: ubuntu-latest

    steps:
      - name: install ffmpeg
        run: sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7 -y;sudo apt update;sudo apt install ffmpeg -y -qq > /dev/null
      - name: live stream
        run: ffmpeg
